# Generated by Django 4.2.2 on 2023-07-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('type', models.IntegerField()),
                ('side', models.IntegerField()),
                ('productType', models.CharField(max_length=100)),
                ('limitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stopPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validity', models.CharField(max_length=100)),
                ('disclosedQty', models.IntegerField()),
                ('offlineOrder', models.BooleanField()),
            ],
        ),
    ]
