# Generated by Django 4.2.2 on 2023-07-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0002_accesstoken_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.TextField(),
        ),
    ]
